// Generated by Selenium IDE
import Utilities.ExtentTestManager;
import com.relevantcodes.extentreports.LogStatus;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.*;

public class bookcartloginviaPortal extends BaseTest{
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void bookCartTest_assertusernamebytouchingportal() {
        try {
            ExtentTestManager.getTest().log(LogStatus.INFO, "bookcart test is starting now", "");
            driver.get("https://bookcart.azurewebsites.net/login");
            driver.manage().window().setSize(new Dimension(1552, 840));
            {
                WebDriverWait wait = new WebDriverWait(driver, 900);
                wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@placeholder=\"Username\"]")));
            }
            driver.findElement(By.xpath("//input[@placeholder=\"Username\"]")).sendKeys("abishekroy");
            driver.findElement(By.xpath("//input[@placeholder=\"Password\"]")).sendKeys("Ankitanku123#");

            driver.findElement(By.xpath("//button[@class=\"mdc-button mdc-button--raised mat-mdc-raised-button mat-primary mat-mdc-button-base\"]")).click();
            Thread.sleep(9000);
            String username=driver.findElement(By.xpath("//a[@class=\"mat-mdc-menu-trigger mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-primary mat-mdc-button-base ng-star-inserted\"]")).getText();
            System.out.println("username" + username);
            if (username.contains("abishekroy")) {

                ExtentTestManager.getTest().log(LogStatus.PASS, "bookcart test is passed ", "");
            }
        }catch (Exception e){
            ExtentTestManager.getTest().log(LogStatus.FAIL, "bookcart test is failed ", ""+e.getMessage());

        }
    }
}
